/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFlowChartView: typeof import('./src/components/TheFlowChartView.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheGraphView: typeof import('./src/components/TheGraphView.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheLeftView: typeof import('./src/components/TheLeftView.vue')['default']
    TheNextIcon: typeof import('./src/components/TheNextIcon.vue')['default']
    ThePdfView: typeof import('./src/components/ThePdfView.vue')['default']
    ThePrevIcon: typeof import('./src/components/ThePrevIcon.vue')['default']
  }
}
